# Generated by Django 3.2.9 on 2024-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Plyometric', 'Plyometric'), ('Bodyweight', 'Bodyweight')], default='Strength', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
