# Generated by Django 3.2.9 on 2024-09-24 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exerciseoftheday_favoriteexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedworkout',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completedworkout',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
